import { Schema } from "mongoose";

import { IProject } from "./schemaTypes";

export const projectSchema = new Schema<IProject>({
  _id: { required: true, type: Number },
  appended_description: { type: String },
  artist: { required: true, type: String },
  artist_address: { required: true, type: String },
  aspect_ratio: { required: true, type: Number },
  chain: { required: true, type: String },
  collection_description: { required: true, type: String },
  collection_image: { type: String },
  collection_name: { required: true, type: String },
  contract_address: { required: true, type: String },
  creation_block: { required: true, type: Number },
  current_supply: { type: Number },
  description: { type: String },
  devParams: {
    isBulkMint: { required: true, type: Boolean },
    useInDev: { required: true, type: Boolean },
    useInProd: { required: true, type: Boolean },
    usesPuppeteer: { required: true, type: Boolean },
    usesScriptInputs: { required: true, type: Boolean },
    usesSvgs: { required: true, type: Boolean },
    usesTokenDataOf: { type: Boolean },
  },
  events: [{ type: String }],
  external_url: { required: true, type: String },
  gen_scripts: {
    alt: { type: String },
    main: { type: String },
    mobileControls: { type: String },
    painting: { type: String },
    preMainScript: { type: String },
    world: { type: String },
  },
  license: { required: true, type: String },
  maximum_supply: { required: true, type: Number },
  mintable: { required: true, type: Boolean },
  project_name: { required: true, type: String },
  project_slug: { required: true, type: String, unique: true },
  royalty_info: {
    additional_payee: { type: String },
    additional_payee_bps: { type: Number },
    artist_address: { type: String },
    charity_address: { type: String },
    royalty_address: { type: String },
    royalty_bps: { type: Number },
    royalty_fee_by_id: { type: Number },
  },
  script_type: { type: String },
  starting_index: { required: true, type: Number },
  tx_count: { required: true, type: Number },
  website: { required: true, type: String },
});
