import { Schema } from "mongoose";

import type { IToken } from "./schemaTypes";

export const tokenSchema = new Schema<IToken>({
  additional_info: {
    additional_description: { type: String },
    poem: { type: String },
  },
  animation_url: { type: String },
  artist: { required: true, type: String },
  artist_address: { required: true, type: String },
  aspect_ratio: { required: true, type: Number },
  attributes: [
    {
      trait_type: { type: String },
      value: { type: Schema.Types.Mixed },
    },
  ],
  collection_name: { required: true, type: String },
  description: { required: true, type: String },
  external_url: { required: true, type: String },
  generator_alt: { type: String },
  generator_mobile: { type: String },
  generator_url: { type: String },
  height_ratio: { type: Number },
  image: { type: String },
  image_data: { type: String },
  image_mid: { type: String },
  image_small: { type: String },
  image_updated_at: { type: Date },
  last_transfer_block: { type: Number },
  license: { required: true, type: String },
  name: { required: true, type: String },
  project_id: { required: true, type: Number },
  project_name: { required: true, type: String },
  project_slug: { required: true, type: String },
  royalty_info: {
    additional_payee: { type: String },
    additional_payee_bps: { type: Number },
    artist_address: { type: String },
    charity_address: { type: String },
    royalty_address: { type: String },
    royalty_bps: { type: Number },
    royalty_fee_by_id: { type: Number },
  },
  script_inputs: {
    approved_shuffler: { type: String },
    audioURI_base: { type: String },
    current_owner: { type: String },
    custom_data: { type: String },
    custom_rule: { type: String },
    description: { type: String },
    imageURI_base: { type: String },
    level_shift: { type: Number },
    media_URI: { type: String },
    previous_owner: { type: String },
    svg_part: { type: String },
    svg_parts: { type: String },
    title: { type: String },
    token_entropy: { type: String },
    token_id: { type: Number },
    transfer_count: { type: Number },
  },
  script_type: { type: String },
  svg: { type: String },
  svgGen: { type: String },
  thumbnail_url: { type: String },
  token_data_frozen: { type: Boolean },
  token_id: { required: true, type: Number },
  transfer_count: { type: Number },
  website: { required: true, type: String },
  width_ratio: { type: Number },
});

tokenSchema.index({ token_id: 1 });
